Update patch set 3
Patch Set 3:

Flake8 Violations: 3
First 6 shown
---
 ./func/driver.py:12:1: E402 module level import not at top of file
 from operator import add
 ^
 ./func/driver.py:13:1: F811 redefinition of unused 'AnsibleApi' from line 10
 from func.ansible_api import AnsibleApi
 ^

Patch-set: 3