Update patch set 1
Patch Set 1:

Flake8 Violations: 2
First 6 shown
---
 ./cli/commands/ansible.py:63:1: W391 blank line at end of file
 
 ^
 ./cli/entry.py:22:1: F811 redefinition of unused 'cli' from line 17
 cli = click.CommandCollection(sources=[ansible.cli])
 ^

Patch-set: 1